import Head from "next/head";
import Link from "next/link";
import React from "react";

export default function Layout({ children, title }) {
  return (
    <>
      <Head>
        <title>{title ? title + "- Amazon" : "Amazon"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex h-14 justify-between items-center shadow-lg  px-4">
            <Link href="/" className="font-bold text-lg">
              Amazona
            </Link>
            <div>
              <Link href="/cart" className="mx-4">
                Cart
              </Link>
              <Link href="/login">Login</Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10  justify-center item-center my-4">
          Copyright @ 2022 - Amazona
        </footer>
      </div>
    </>
  );
}
